framework:
    messenger:
        failure_transport: failed

        transports:
            async:
                dsn: 'in-memory://'
                retry_strategy:
                    max_retries: 3
                    multiplier: 2

            failed: 'in-memory://'

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
            App\Users\Event\UserCreatedEvent: async
