version: '3.7'

services:
  app:
    build: .
    ports:
      - '8000:80'
    volumes:
      - .:/var/www/html
    depends_on:
      - rabbitmq

  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'
